### PR TITLE
first draft of new home for describing the organizing committe

### LINKED ISSUE #25: committee
as with speakers #24, we plan to show in homepage the name of commitee members

### PR DESCRIPTION
**Pull request by Marco-Santoni**
Closes #25  and #6

Removed any reference to the committee at the top of the home
image

Moved the news and updated downwards.

Created new Organizers and Communities section. External links were removed on purpose.
image

### CODE REVIEW

**Comment by pietroppeter** [comment]
I like the idea to focus on value for speakers in the initial description (and not on who does what). Before merging I would fix the alignment.

**Comment by pietroppeter** [comment]
during meeting, before merging:
- fix aligment
- remove paragraphs on ARGO and SEA (to be reviewed and updated later)
I will try to help on this

**Comment by Marco-Santoni** [comment]
> I like the idea to focus on value for speakers in the initial description (and not on who does what). Before merging I would fix the alignment.

Agree, but I'll postpone this as I won't make it today. We go live disaligned and fix it asap.

**Comment by Marco-Santoni** [comment]
Paragraphs removed. Alignment not fixed in this PR
image

**Pull request merged**
